agent:
  key: greedy_decision_tree_4
  resource:
    model@catboost: "/kaggle/input/my-santa-2020-data/top_agents_catboost_regression_model_add_feats_depth_8.cbm"
  name: top_agents_catboost_add_feats_8
