train_data_folds:
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_0_4.parquet
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_1_4.parquet
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_2_4.parquet
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_3_4.parquet
val_data_folds:
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_4_4.parquet
train_feats:
  - round_num
  - n_pulls_self
  - n_success_self
  - n_pulls_opp
  - n_pulls
  - decay
target: payout
model_module: lightgbm
model_type: LGBMRegressor
model_name: top_agents_lightgbm_regression_model_2
