train_data_folds:
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_0_4.parquet
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_1_4.parquet
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_2_4.parquet
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_3_4.parquet
val_data_folds:
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_4_4.parquet
train_feats:
  - round_num
  - n_pulls_self
  - n_success_self
  - n_pulls_opp
target: payout
model_name: top_agents_catboost_regression_model_deep
construct_params:
  use_best_model: true
  eval_metric: RMSE
  depth: 10
