train_data_folds:
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_0_4.parquet
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_1_4.parquet
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_2_4.parquet
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_3_4.parquet
val_data_folds:
  - /kaggle/input/my-santa-2020-data/top_agents_training_data_210106.parquet_4_4.parquet
train_feats:
  - round_num
  - n_pulls_self
  - n_success_self
  - n_pulls_opp
target: payout
model_module: sklearn.tree
model_type: DecitionTreeRegressor
model_name: top_agents_decition_tree_regression_model
train_params:
  min_samples_leaf: 40
