data_file: "/kaggle/input/sample-training-data/training_data_201223.parquet"
train_feats:
  - round_num
  - n_pulls_self
  - n_success_self
  - n_pulls_opp
target: payout
model_name: simple_decitoin_tree_regression_model
train_params:
  min_samples_leaf: 40
